### ISSUE TITLE
[FEAT] 플레이어 이동 구현

### ISSUE THREAD

**Issue by gojjang10** [gojjang10/UnityMiniProject#1]
플레이어(마리오)의 이동 구현하기

**Comment by gojjang10** [comment]
Rigidbody2D를 사용해서 움직임 구현 완료

**Comment by gojjang10** [comment]
플레이어(마리오)의 움직임을 Idle, Walk, Jump 상태로 나누고 상태패턴을 적용하여 직관적으로 구현

**Comment by gojjang10** [comment]
시네머신 카메라를 사용하여 플레이어(마리오)를 따라가게 설정

**Comment by jungtaek6681** [comment]
잘했으 이대로 계속 진행!
